language: go

go:
  - 1.12.x
  - 1.13.x
  - tip

install: true

before_script:
  - go get github.com/go-chi/chi
  - go get github.com/stretchr/testify

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
