language: go

go:
  - 1.11.1

install: true

before_script:
  - go get -d ./...

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
